export type LanguageCode =
  | "En" | "EnUs" | "EnGb" | "EnAu" | "EnCa" | "EnIn" | "EnIe" | "EnNz" | "EnZa" | "EnSg" | "EnPh"
  | "Es" | "EsEs" | "EsMx" | "EsUs" | "EsAr" | "EsCo" | "EsCl" | "EsPe"
  | "Fr" | "FrFr" | "FrCa" | "FrBe" | "FrCh"
  | "De" | "DeDe" | "DeAt" | "DeCh"
  | "Pt" | "PtBr" | "PtPt"
  | "It" | "ItIt" | "ItCh"
  | "Nl" | "NlNl" | "NlBe"
  | "Zh" | "ZhCn" | "ZhTw" | "ZhHk"
  | "Bn" | "BnIn" | "BnBd"
  | "Ta" | "TaIn" | "TaLk"
  | "Ar" | "ArSa" | "ArAe" | "ArEg"
  | "Mt" | "El" | "Tr" | "He"
  | "Da" | "Sv" | "Nb" | "Fi" | "Is"
  | "Pl" | "Cs" | "Sk" | "Hu" | "Ro" | "Bg" | "Hr" | "Sr" | "Sl" | "Uk" | "Ru"
  | "Ca" | "Eu" | "Gl" | "Ga" | "Cy"
  | "Ja" | "Ko" | "Th" | "Vi" | "Id" | "Ms" | "Tl"
  | "Hi" | "Te" | "Mr" | "Gu" | "Kn" | "Ml" | "Pa" | "Ur"
  | "Fa" | "Az" | "Kk" | "Uz" | "Hy" | "Ka"
  | "Sw" | "Af" | "Am" | "Zu" | "Yo" | "Ha";
